---
title: "The Impact of Network Architecture and Network Type of Neural Networks on Trading Performance"
subtitle: "OEKO3 Final Project"
author: Pascal Bühler, Ken Geeler, Philipp Rieser
date: "Spring Semester 2021"
output: 
  pdf_document:
    toc: no
    df_print: paged
bibliography: add/doc.bib
linkcolor: red
csl:  add/ieee.csl
header-includes:
- \usepackage{pdfpages}
- \usepackage{amsmath}
- \usepackage{placeins} # to keep figures and text in the order you wrote them

abstract:
  "The use of neural networks and their utility in financial time series is a frequently studied topic. Plain vanilla feedforward neural networks, recurrent neural networks (RNN), gated recurrent unit (GRU), and long short-term memory (LSTM) are applied and compared. The impact of the choice of a specific network type and network architecture (number of layers and neurons) on trading performance is investigated. Using a fixed in-sample and out-of-sample, all possible combinations between the simplest (one layer and one neuron) and the most complex network (three layers and ten neurons) are trained and their trading performance is quantified and compared to the Buy and Hold Benchmark. The results of the recurrent networks are disappointing regarding financial time series, however, feed forward nets are worth pursuing and further investigating."
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r knitr.global_options, include=F}
knitr::opts_chunk$set(out.width = "70%", fig.align = "center", echo=FALSE, warning=FALSE, message=FALSE, tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

```{r }
source("add/libraries.R")
source("add/Functions_RNN.R")
```

\pagenumbering{gobble}
\newpage

```{=tex}
\setcounter{tocdepth}{4}
\tableofcontents
```

\newpage
\pagenumbering{arabic}

```{r child= "01_introduction.Rmd"}
```

```{r child= "02_theory.Rmd"}
```

\newpage

```{r child= "03_methods.Rmd"}
```

\newpage

```{r child= "04_results.Rmd"}
```

\newpage

```{r child= "05_conclusion.Rmd"}
```

\newpage

```{r child= "06_references.Rmd"}
```

\newpage

```{r child= "07_attachment.Rmd"}
```

