## 1. Introduction {#introduction}

Ever since Siri was launched by Apple in 2011, people outside the world of science began to have a rough idea of what artificial intelligence is. While these topics have gained more and more popularity since then and are often one of the main topics at global conferences, the application potential must be considered realistically. Although the application of neural networks in the just mentioned natural language processing (NLP) is reasonable, the opinion is split in the application in the field of financial time series. Since a large part of movements of financial instruments are based on white noise and thus have almost no dependency structure, the implementation of a meaningful method is challenging. Likewise, an integration of neural networks only makes sense if a profit can be achieved - for instance, in the case of financial data as a result of trading. This paper will deal exactly with this topic. Simple feedforward networks (FFN) and recurrent neural networks (RNN) will be trained. Then, based on the trained networks, a simple trading strategy will be applied to assess whether it adds value to a potential investor. 