## 7. Attachment {#attachement}

This work is created  with R-4.0.2 , RStudio Version 1.4.904 and RMarkdown in collaborative working via Git / Github
https://github.com/majimaken/econometrics-3-project


```{r attachment1, fig.align='center', out.width='90%', fig.cap='The upper plot shows the original values. In the lower plot, the values with 1 or 2 neurons in the last layer have been removed.', echo=FALSE, fig.width = 12, fig.height = 8}

ones <- seq(11, 1110, 10)
twos <- seq(12, 1110, 10)

big_index_rnn1 <- ones
big_index_rnn2 <- twos

big_index_lstm1 <- ones
big_index_lstm2 <- twos

big_index_gru1 <- ones
big_index_gru2 <- twos



rnn12 <- mean_rnn$mse_in
rnn12[big_index_rnn1] <- NA
rnn12[big_index_rnn2] <- NA

lstm12 <- mean_lstm$mse_in
lstm12[big_index_lstm1] <- NA
lstm12[big_index_lstm2] <- NA

gru12 <- mean_gru$mse_in
gru12[big_index_gru1] <- NA
gru12[big_index_gru2] <- NA



par_default <- par(no.readonly = TRUE)
par(mfrow=c(2,1), mar=c(4,5,3,2))

plot(mean_rnn$mse_in, type="l", col=2, xlab="", ylab="MSE in", main="Original", xaxt="n",
     frame.plot = FALSE)
lines(mean_lstm$mse_in, col=3)
lines(mean_gru$mse_in, col=4)
axis(1, at=c(1, 110, 222, 444, 666, 888, 1110),
     labels=c("(1)", "(10,10)", "(2,2,2)","(4,4,4)", "(6,6,6)", "(8,8,8)", "(10,10,10)"))
rect(xleft=1,
     xright=10,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#FF00001A")

rect(xleft=11,
     xright=110,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#00FFFF1A")

rect(xleft=111,
     xright=1110,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#8000FF1A")

plot(rnn12, type="l", col=2, xlab="", ylab="MSE in", main="Correction", xaxt="n",
     frame.plot = FALSE,)
lines(lstm12, col=3)
lines(gru12, col=4)
axis(1, at=c(1, 110, 222, 444, 666, 888, 1110),
     labels=c("(1)", "(10,10)", "(2,2,2)","(4,4,4)", "(6,6,6)", "(8,8,8)", "(10,10,10)"))
rect(xleft=1,
     xright=10,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#FF00001A")

rect(xleft=11,
     xright=110,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#00FFFF1A")

rect(xleft=111,
     xright=1110,
     ybottom=par('usr')[3],
     ytop=par('usr')[4],
     col="#8000FF1A")
par(par_default)


```


```{r LSTM, fig.align='center', out.width='90%', fig.keep="last",fig.cap='GRU out of sample', echo=FALSE, fig.width = 12, fig.height = 8}



##lstm
anz=100
plot(perfnew_lstm,col=c("blue","black",rep("grey",anz)),lwd=c(7,7,rep(1,anz)),main="Out of sample Perfomance LSTM")

name=c("Buy and Hold","Mean of Nets")
addLegend("topleft", 
          legend.names=name,
          col=c("black","blue"),
          lty=rep(1,1),
          lwd=rep(2,2),
          ncol=1,
          bg="white")



```

```{r rnn, fig.align='center', out.width='90%', fig.cap='RNN out of sample', echo=FALSE, fig.width = 12, fig.height = 8,fig.keep="last"}

##rnn
anz=100
plot(perfnew_rnn,col=c("orange","black",rep("grey",anz)),lwd=c(7,7,rep(1,anz)),main="Out of sample Perfomance rnn")

name=c("Buy and Hold","Mean of Nets")
addLegend("topleft", 
          legend.names=name,
          col=c("black","orange"),
          lty=rep(1,1),
          lwd=rep(2,2),
          ncol=1,
          bg="white")
```

```{r gru, fig.align='center', out.width='90%',fig.keep="last", fig.cap='GRU out of sample', echo=FALSE, fig.width = 12, fig.height = 8}

##gru
anz=100
plot(perfnew_gru,col=c("green","black",rep("grey",anz)),lwd=c(7,7,rep(1,anz)),main="Out of sample Perfomance GRU")

name=c("Buy and Hold","Mean of Nets")
addLegend("topleft", 
          legend.names=name,
          col=c("black","green"),
          lty=rep(1,1),
          lwd=rep(2,2),
          ncol=1,
          bg="white")
```