# all libraries 
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(quantmod)
library(forecast)
library(devtools)
library(TTR)
#library(MDFA)
library(neuralnet)
#library(neuralnet)
library(boot)
library(MASS)
library(retry) # exception handling in neuralnet
library(lubridate)
library(keras)

library(rnn)
library(boot)
library(plyr) 
library(fGarch)
library(Quandl)
